// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250714144548_Add_Balance_To_CheckingAccount")]
    partial class Add_Balance_To_CheckingAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CheckingAccount", b =>
                {
                    b.Property<byte[]>("CheckingAccountId")
                        .HasColumnType("RAW(36)")
                        .HasColumnName("idContaCorrente");

                    b.Property<int>("AccountNumber")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("numero");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("saldo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("nome");

                    b.Property<int>("IsActive")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ativo");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)")
                        .HasColumnName("senha");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("salt");

                    b.HasKey("CheckingAccountId");

                    b.ToTable("ContaCorrente", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Idempotency", b =>
                {
                    b.Property<byte[]>("IdempotencyKey")
                        .HasColumnType("RAW(36)")
                        .HasColumnName("chaveIdempotencia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("RequestId")
                        .IsRequired()
                        .HasColumnType("RAW(36)")
                        .HasColumnName("requisicao");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("resultado");

                    b.HasKey("IdempotencyKey");

                    b.ToTable("Idempotencia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.Property<byte[]>("TransactionId")
                        .HasColumnType("RAW(36)")
                        .HasColumnName("idMovimento");

                    b.Property<byte[]>("AccountId")
                        .IsRequired()
                        .HasColumnType("RAW(36)")
                        .HasColumnName("idContaCorrente");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("valor");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("tipoMovimento");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.ToTable("Movimento", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Domain.Entities.CheckingAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_ContaCorrente");

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
