version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: SenhaForte123
      ORACLE_DATABASE: XEPDB1
      ORACLE_ALLOW_REMOTE: "true"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  oracle-data:
