// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<string>("IdContaCorrente")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("idContaCorrente");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ativo");

                    b.Property<long>("Cpf")
                        .HasColumnType("NUMBER(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(128)")
                        .HasColumnName("salt");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(512)")
                        .HasColumnName("senha");

                    b.HasKey("IdContaCorrente");

                    b.ToTable("ContaCorrente", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
