// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TransferMS.Infrastructure.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250715003529_Initial_Create")]
    partial class Initial_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransferMS.Domain.Entities.Idempotency", b =>
                {
                    b.Property<byte[]>("IdempotencyKey")
                        .HasColumnType("RAW(36)")
                        .HasColumnName("chaveIdempotencia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("RequestId")
                        .IsRequired()
                        .HasColumnType("RAW(36)")
                        .HasColumnName("requisicao");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("resultado");

                    b.HasKey("IdempotencyKey");

                    b.ToTable("Idempotencia", (string)null);
                });

            modelBuilder.Entity("TransferMS.Domain.Entities.Transfer", b =>
                {
                    b.Property<string>("TransferId")
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("idTransferencia");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("valor");

                    b.Property<string>("IdCheckingAccountFrom")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("idContaCorrenteOrigem");

                    b.Property<string>("IdCheckingAccountTo")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("idContaCorrenteDestino");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("dataTransferencia");

                    b.HasKey("TransferId");

                    b.ToTable("Transferencia", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
